# importing libraries

In [1]:
import pandas as pd
import numpy as np

# loading the dataset

In [2]:
data = pd.read_csv("KNN for missing year.csv")
data.head()

,Total Project Cost,Size Of Home,size_of_home_flag,Number Of Units,Location_1_latitude,Location_1_Longitude,Project Completion Date,Job Type,Type Of Dwelling,Pre-Retrofit Home Heating Fuel Type,Year Home Built
0,9661.0,1484,0,1,42.110115,-76.032545,2023-06-22,Home Performance,Single Family,Oil,NaN
1,11867.0,1664,0,1,40.697715,-73.786045,2023-06-22,Home Performance,Single Family,Natural Gas,NaN
2,9998.0,1252,0,1,43.325035,-76.411740,2023-06-20,Home Performance,Single Family,Natural Gas,NaN
3,6880.0,1700,0,1,44.695165,-74.704765,2023-06-13,Home Performance,Single Family,Oil,NaN
4,12289.0,2680,0,1,43.231255,-75.868192,2023-06-13,Home Performance,Single Family,Oil,NaN

In [3]:
data.describe()

,Total Project Cost,Size Of Home,size_of_home_flag,Number Of Units,Location_1_latitude,Location_1_Longitude
count,51934.000000,51934.000000,51934.0,51934.000000,51934.000000,51934.000000
mean,6432.440848,1572.731717,0.0,1.058074,42.488912,-76.116195
std,4154.131692,627.668989,0.0,2.175599,0.970511,1.834420
min,129.000000,800.000000,0.0,1.000000,40.542400,-79.745086
25%,3742.000000,1111.000000,0.0,1.000000,42.084960,-77.636890
50%,5926.000000,1440.000000,0.0,1.000000,42.929765,-76.112650
75%,8462.000000,1874.000000,0.0,1.000000,43.133750,-74.044827
max,92297.000000,4000.000000,0.0,396.000000,44.989856,-72.186670

In [4]:
data.dtypes

Total Project Cost                     float64
Size Of Home                             int64
size_of_home_flag                        int64
Number Of Units                          int64
Location_1_latitude                    float64
Location_1_Longitude                   float64
Project Completion Date                 object
Job Type                                object
Type Of Dwelling                        object
Pre-Retrofit Home Heating Fuel Type     object
Year Home Built                         object
dtype: object

In [5]:
data['Project Completion Date']

0        2023-06-22
1        2023-06-22
2        2023-06-20
3        2023-06-13
4        2023-06-13
            ...
51929    2019-07-26
51930    2018-11-09
51931    2018-11-12
51932    2019-05-21
51933    2019-01-15
Name: Project Completion Date, Length: 51934, dtype: object

# Converting the project completion datatype

In [6]:
data['Project Completion Date'] = pd.to_datetime(data['Project Completion Date'], format = "%Y-%m-%d")

In [7]:
import datetime as dt
data['Project Completion Year'] = data['Project Completion Date'].dt.year
data['Project Completion month'] = data['Project Completion Date'].dt.month
data['Project Completion Day'] = data['Project Completion Date'].dt.day

In [8]:
data.drop(columns="Project Completion Date" , inplace= True)

In [9]:
data.head()

,Total Project Cost,Size Of Home,size_of_home_flag,Number Of Units,Location_1_latitude,Location_1_Longitude,Job Type,Type Of Dwelling,Pre-Retrofit Home Heating Fuel Type,Year Home Built,Project Completion Year,Project Completion month,Project Completion Day
0,9661.0,1484,0,1,42.110115,-76.032545,Home Performance,Single Family,Oil,NaN,2023,6,22
1,11867.0,1664,0,1,40.697715,-73.786045,Home Performance,Single Family,Natural Gas,NaN,2023,6,22
2,9998.0,1252,0,1,43.325035,-76.411740,Home Performance,Single Family,Natural Gas,NaN,2023,6,20
3,6880.0,1700,0,1,44.695165,-74.704765,Home Performance,Single Family,Oil,NaN,2023,6,13
4,12289.0,2680,0,1,43.231255,-75.868192,Home Performance,Single Family,Oil,NaN,2023,6,13

In [10]:
data.dtypes

Total Project Cost                     float64
Size Of Home                             int64
size_of_home_flag                        int64
Number Of Units                          int64
Location_1_latitude                    float64
Location_1_Longitude                   float64
Job Type                                object
Type Of Dwelling                        object
Pre-Retrofit Home Heating Fuel Type     object
Year Home Built                         object
Project Completion Year                  int32
Project Completion month                 int32
Project Completion Day                   int32
dtype: object

# Target variable

In [11]:
data['Year Home Built'] = data['Year Home Built'].replace("<1800", 1790)
data['Year Home Built'] = pd.to_numeric(data['Year Home Built'])

# Filtering categorical columns

In [12]:
cat_col = []
num_col =[]
for i in data.columns:
    if data[i].dtypes == "object":
        cat_col.append(i)
    else:
        num_col.append(i)

In [13]:
cat_col_df = data[cat_col]
cat_col_df

               Job Type Type Of Dwelling Pre-Retrofit Home Heating Fuel Type
0      Home Performance    Single Family                                 Oil
1      Home Performance    Single Family                         Natural Gas
2      Home Performance    Single Family                         Natural Gas
3      Home Performance    Single Family                                 Oil
4      Home Performance    Single Family                                 Oil
...                 ...              ...                                 ...
51929  Home Performance    Single Family                         Natural Gas
51930  Home Performance    Single Family                         Natural Gas
51931  Home Performance    Single Family                         Natural Gas
51932  Home Performance    Single Family                         Natural Gas
51933  Home Performance    Single Family                                 Oil

[51934 rows x 3 columns]

In [14]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
for col in cat_col_df.columns:
    # fit_transform handles one column at a time
    cat_col_df[col] = le.fit_transform(cat_col_df[col])

/var/folders/lz/gg3608196pgcm29rnqq45xtm0000gn/T/ipykernel_77160/2133823814.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cat_col_df[col] = le.fit_transform(cat_col_df[col])
/var/folders/lz/gg3608196pgcm29rnqq45xtm0000gn/T/ipykernel_77160/2133823814.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cat_col_df[col] = le.fit_transform(cat_col_df[col])
/var/folders/lz/gg3608196pgcm29rnqq45xtm0000gn/T/ipykernel_77160/2133823814.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cat_col_df[col] = le.fit_transform(cat_col_df[col])

In [15]:
cat_col_df

       Job Type  Type Of Dwelling  Pre-Retrofit Home Heating Fuel Type
0             1                 2                                    4
1             1                 2                                    3
2             1                 2                                    3
3             1                 2                                    4
4             1                 2                                    4
...         ...               ...                                  ...
51929         1                 2                                    3
51930         1                 2                                    3
51931         1                 2                                    3
51932         1                 2                                    3
51933         1                 2                                    4

[51934 rows x 3 columns]

In [16]:
data['Job Type'] = cat_col_df['Job Type']
data['Type Of Dwelling'] = cat_col_df['Type Of Dwelling']
data['Pre-Retrofit Home Heating Fuel Type'] = cat_col_df['Pre-Retrofit Home Heating Fuel Type']

In [17]:
data.head()

,Total Project Cost,Size Of Home,size_of_home_flag,Number Of Units,Location_1_latitude,Location_1_Longitude,Job Type,Type Of Dwelling,Pre-Retrofit Home Heating Fuel Type,Year Home Built,Project Completion Year,Project Completion month,Project Completion Day
0,9661.0,1484,0,1,42.110115,-76.032545,1,2,4,NaN,2023,6,22
1,11867.0,1664,0,1,40.697715,-73.786045,1,2,3,NaN,2023,6,22
2,9998.0,1252,0,1,43.325035,-76.411740,1,2,3,NaN,2023,6,20
3,6880.0,1700,0,1,44.695165,-74.704765,1,2,4,NaN,2023,6,13
4,12289.0,2680,0,1,43.231255,-75.868192,1,2,4,NaN,2023,6,13

In [18]:
data.dtypes

Total Project Cost                     float64
Size Of Home                             int64
size_of_home_flag                        int64
Number Of Units                          int64
Location_1_latitude                    float64
Location_1_Longitude                   float64
Job Type                                 int64
Type Of Dwelling                         int64
Pre-Retrofit Home Heating Fuel Type      int64
Year Home Built                        float64
Project Completion Year                  int32
Project Completion month                 int32
Project Completion Day                   int32
dtype: object

# Standard Scaling

In [19]:
from sklearn.preprocessing import StandardScaler

StandardScaler = StandardScaler()
data_scaled = StandardScaler.fit_transform(data)

In [20]:
data_scaled

array([[ 0.77719978, -0.14136842,  0.        , ...,  1.44047018,
        -0.01220874,  0.71609974],
       [ 1.30824246,  0.1454097 ,  0.        , ...,  1.44047018,
        -0.01220874,  0.71609974],
       [ 0.85832461, -0.51099355,  0.        , ...,  1.44047018,
        -0.01220874,  0.48494777],
       ...,
       [-0.84288964, -0.47434968,  0.        , ..., -1.46915521,
         1.45346129, -0.43966008],
       [-0.14069041, -0.46638362,  0.        , ..., -0.88723013,
        -0.30534275,  0.60052376],
       [-0.56797996, -0.09994491,  0.        , ..., -0.88723013,
        -1.47787878, -0.09293213]])

In [21]:
num_col_df_scaled = pd.DataFrame(data_scaled, columns=data.columns)

num_col_df_scaled.head()

,Total Project Cost,Size Of Home,size_of_home_flag,Number Of Units,Location_1_latitude,Location_1_Longitude,Job Type,Type Of Dwelling,Pre-Retrofit Home Heating Fuel Type,Year Home Built,Project Completion Year,Project Completion month,Project Completion Day
0,0.777200,-0.141368,0.0,-0.026693,-0.390311,0.045600,0.200652,0.373201,0.393910,NaN,1.44047,-0.012209,0.716100
1,1.308242,0.145410,0.0,-0.026693,-1.845640,1.270250,0.200652,0.373201,-0.364612,NaN,1.44047,-0.012209,0.716100
2,0.858325,-0.510994,0.0,-0.026693,0.861536,-0.161113,0.200652,0.373201,-0.364612,NaN,1.44047,-0.012209,0.484948
3,0.107739,0.202765,0.0,-0.026693,2.273311,0.769422,0.200652,0.373201,0.393910,NaN,1.44047,-0.012209,-0.324084
4,1.409829,1.764113,0.0,-0.026693,0.764906,0.135195,0.200652,0.373201,0.393910,NaN,1.44047,-0.012209,-0.324084

# Imputing Year

In [22]:
from sklearn.impute import KNNImputer

year_imputer = KNNImputer(n_neighbors= 5, weights="distance")
knn_year_imputed = year_imputer.fit_transform(data_scaled)

In [23]:
knn_year_imputed = StandardScaler.inverse_transform(knn_year_imputed)
knn_year_imputed_df = pd.DataFrame(knn_year_imputed, columns=data.columns, index=data.index)

In [24]:
knn_year_imputed_df

,Total Project Cost,Size Of Home,size_of_home_flag,Number Of Units,Location_1_latitude,Location_1_Longitude,Job Type,Type Of Dwelling,Pre-Retrofit Home Heating Fuel Type,Year Home Built,Project Completion Year,Project Completion month,Project Completion Day
0,9661.0,1484.0,0.0,1.0,42.110115,-76.032545,1.0,2.0,4.0,1960.395042,2023.0,6.0,22.0
1,11867.0,1664.0,0.0,1.0,40.697715,-73.786045,1.0,2.0,3.0,1933.416002,2023.0,6.0,22.0
2,9998.0,1252.0,0.0,1.0,43.325035,-76.411740,1.0,2.0,3.0,1943.607648,2023.0,6.0,20.0
3,6880.0,1700.0,0.0,1.0,44.695165,-74.704765,1.0,2.0,4.0,1913.331740,2023.0,6.0,13.0
4,12289.0,2680.0,0.0,1.0,43.231255,-75.868192,1.0,2.0,4.0,1901.306930,2023.0,6.0,13.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
51929,7984.0,3628.0,0.0,1.0,41.190952,-74.034430,1.0,2.0,3.0,1952.012127,2019.0,7.0,26.0
51930,4678.0,1456.0,0.0,1.0,42.935500,-76.566870,1.0,2.0,3.0,1921.000000,2018.0,11.0,9.0
51931,2931.0,1275.0,0.0,1.0,42.726280,-73.688825,1.0,2.0,3.0,1921.000000,2018.0,11.0,12.0
51932,5848.0,1280.0,0.0,1.0,40.723510,-73.737980,1.0,2.0,3.0,1928.000000,2019.0,5.0,21.0
51933,4073.0,1510.0,0.0,1.0,43.236110,-77.064890,1.0,2.0,4.0,1936.482028,2019.0,1.0,15.0

In [25]:
knn_year_imputed_df["Year Home Built"] = knn_year_imputed_df["Year Home Built"].round()

In [26]:
knn_year_imputed_df.isnull().sum()

Total Project Cost                     0
Size Of Home                           0
size_of_home_flag                      0
Number Of Units                        0
Location_1_latitude                    0
Location_1_Longitude                   0
Job Type                               0
Type Of Dwelling                       0
Pre-Retrofit Home Heating Fuel Type    0
Year Home Built                        0
Project Completion Year                0
Project Completion month               0
Project Completion Day                 0
dtype: int64

In [27]:
knn_year_imputed_df["Year Home Built"] = knn_year_imputed_df['Year Home Built'].astype(int)

In [28]:
data = knn_year_imputed_df
data.head()

,Total Project Cost,Size Of Home,size_of_home_flag,Number Of Units,Location_1_latitude,Location_1_Longitude,Job Type,Type Of Dwelling,Pre-Retrofit Home Heating Fuel Type,Year Home Built,Project Completion Year,Project Completion month,Project Completion Day
0,9661.0,1484.0,0.0,1.0,42.110115,-76.032545,1.0,2.0,4.0,1960,2023.0,6.0,22.0
1,11867.0,1664.0,0.0,1.0,40.697715,-73.786045,1.0,2.0,3.0,1933,2023.0,6.0,22.0
2,9998.0,1252.0,0.0,1.0,43.325035,-76.411740,1.0,2.0,3.0,1944,2023.0,6.0,20.0
3,6880.0,1700.0,0.0,1.0,44.695165,-74.704765,1.0,2.0,4.0,1913,2023.0,6.0,13.0
4,12289.0,2680.0,0.0,1.0,43.231255,-75.868192,1.0,2.0,4.0,1901,2023.0,6.0,13.0

In [29]:
data['Year Home Built'].describe()

count    51934.000000
mean      1948.107868
std         29.295404
min       1790.000000
25%       1931.000000
50%       1948.000000
75%       1966.000000
max       2022.000000
Name: Year Home Built, dtype: float64

In [30]:
data.shape

(51934, 13)

# Pushing the year column back to the main preprocessed dataset

In [31]:
year_missing_df = pd.read_csv("Preprocessed_dataset.csv")

/var/folders/lz/gg3608196pgcm29rnqq45xtm0000gn/T/ipykernel_77160/88406272.py:1: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  year_missing_df = pd.read_csv("Preprocessed_dataset.csv")

In [32]:
year_missing_df.head()

,Reporting Period,Project ID,Project County,Project City,Project ZIP,Gas Utility,Electric Utility,Project Completion Date,Total Project Cost,Pre-Retrofit Home Heating Fuel Type,...,Type Of Dwelling,Measure Type,Estimated Annual kWh Savings,Estimated Annual MMBtu Savings,First Year Modeled Project Energy Savings $ Estimate,size_of_home_flag,Home Built Year Range,Project Cost Range,Location_1_latitude,Location_1_Longitude
0,2023-06-30,577366,Broome,Endicott,13760,New York State Electric & Gas,New York State Electric & Gas,2023-06-22,9661.0,Oil,...,Single Family,Building Shell,277.0,24.0,6.826545,0,1950 - 2000,1000 - 10000,42.110115,-76.032545
1,2023-06-30,581070,Queens,Queens,11433,National Grid,Consolidated Edison,2023-06-22,11867.0,Natural Gas,...,Single Family,Building Shell,1062.0,66.0,7.221105,0,1950 - 2000,10000 - 20000,40.697715,-73.786045
2,2023-06-30,570945,Oswego,Fulton,13069,National Grid,National Grid,2023-06-20,9998.0,Natural Gas,...,Single Family,Building Shell,59.0,60.0,6.489205,0,1900 - 1950,1000 - 10000,43.325035,-76.411740
3,2023-06-30,571921,St. Lawrence,Nicholville,12965,Saint Lawrence Gas,National Grid,2023-06-13,6880.0,Oil,...,Single Family,Building Shell,482.0,15.0,6.445720,0,1950 - 2000,1000 - 10000,44.695165,-74.704765
4,2023-06-30,555646,Oswego,Cleveland,13042,National Grid,National Grid,2023-06-13,12289.0,Oil,...,Single Family,Building Shell,690.0,78.0,7.490529,0,1850-1900,10000 - 20000,43.231255,-75.868192

In [33]:
year_missing_df.isnull().sum()

Reporting Period                                            0
Project ID                                                  0
Project County                                              0
Project City                                                0
Project ZIP                                                 0
Gas Utility                                                 0
Electric Utility                                            0
Project Completion Date                                     0
Total Project Cost                                          0
Pre-Retrofit Home Heating Fuel Type                         0
Year Home Built                                         31153
Size Of Home                                                0
Number Of Units                                             0
Job Type                                                    0
Type Of Dwelling                                            0
Measure Type                                                0
Estimated Annual kWh Savings                                0
Estimated Annual MMBtu Savings                              0
First Year Modeled Project Energy Savings $ Estimate        4
size_of_home_flag                                           0
Home Built Year Range                                    4158
Project Cost Range                                          0
Location_1_latitude                                         0
Location_1_Longitude                                        0
dtype: int64

In [34]:
year_missing_df.shape

(51934, 24)

In [35]:
data.shape

(51934, 13)

In [36]:
year_missing_df['Year Home Built'] = data['Year Home Built']

In [37]:
year_missing_df.isnull().sum()

Reporting Period                                           0
Project ID                                                 0
Project County                                             0
Project City                                               0
Project ZIP                                                0
Gas Utility                                                0
Electric Utility                                           0
Project Completion Date                                    0
Total Project Cost                                         0
Pre-Retrofit Home Heating Fuel Type                        0
Year Home Built                                            0
Size Of Home                                               0
Number Of Units                                            0
Job Type                                                   0
Type Of Dwelling                                           0
Measure Type                                               0
Estimated Annual kWh Savings                               0
Estimated Annual MMBtu Savings                             0
First Year Modeled Project Energy Savings $ Estimate       4
size_of_home_flag                                          0
Home Built Year Range                                   4158
Project Cost Range                                         0
Location_1_latitude                                        0
Location_1_Longitude                                       0
dtype: int64

In [38]:
year_missing_df.drop(columns= ["Home Built Year Range","Project Cost Range"], inplace= True)

In [39]:
year_missing_df.isnull().sum()

Reporting Period                                        0
Project ID                                              0
Project County                                          0
Project City                                            0
Project ZIP                                             0
Gas Utility                                             0
Electric Utility                                        0
Project Completion Date                                 0
Total Project Cost                                      0
Pre-Retrofit Home Heating Fuel Type                     0
Year Home Built                                         0
Size Of Home                                            0
Number Of Units                                         0
Job Type                                                0
Type Of Dwelling                                        0
Measure Type                                            0
Estimated Annual kWh Savings                            0
Estimated Annual MMBtu Savings                          0
First Year Modeled Project Energy Savings $ Estimate    4
size_of_home_flag                                       0
Location_1_latitude                                     0
Location_1_Longitude                                    0
dtype: int64

In [40]:
year_missing_df.to_csv("Preprocessed_dataset_knn(5neighbour).csv")

# neighbour comparision

In [41]:
n3 = pd.read_csv("Preprocessed_dataset_knn(3neighbour).csv")
n5 = pd.read_csv("Preprocessed_dataset_knn(5neighbour).csv")

/var/folders/lz/gg3608196pgcm29rnqq45xtm0000gn/T/ipykernel_77160/2666121416.py:1: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  n3 = pd.read_csv("Preprocessed_dataset_knn(3neighbour).csv")
/var/folders/lz/gg3608196pgcm29rnqq45xtm0000gn/T/ipykernel_77160/2666121416.py:2: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  n5 = pd.read_csv("Preprocessed_dataset_knn(5neighbour).csv")

In [42]:
n3['Year Home Built'].describe()

count    51934.000000
mean      1948.124889
std         30.889709
min       1790.000000
25%       1930.000000
50%       1949.000000
75%       1969.000000
max       2022.000000
Name: Year Home Built, dtype: float64

In [43]:
n5['Year Home Built'].describe()

count    51934.000000
mean      1948.107868
std         29.295404
min       1790.000000
25%       1931.000000
50%       1948.000000
75%       1966.000000
max       2022.000000
Name: Year Home Built, dtype: float64